### ISSUE TITLE
Consider Web Worker usage

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/sinergia#3]
It could be an idea also to use [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to execute the computations in parallel.

### Advantages
1. It's *really* in background and in a separate thread. So the task doesn't even need to `yield` I think and should be more efficient than `requestAnimationFrame`
2. Could be simpler for the user since the task doesn't need to be a generator or to `yield`

### Disadvantages
1. You cannot pass object references so it requires object serialization and it could be a bottleneck
2. Browser support [starts from IE10](http://caniuse.com/#feat=webworkers). Not dramatic but could an issue for someone, whereas `requestAnimationFrame` can be polyfilled with `setTimeout`. We could add an option to specify how to run the tasks.
3. Cannot be used if the computation requires access to DOM, but I don't think it's a frequent case with data manipulation.
4. Much harder to setup. Web Workers require separate JS file whereas [inline solutions](http://stackoverflow.com/questions/5408406/web-workers-without-a-separate-javascript-file
) seem tricky.

**Comment by MichaReiser** [comment]
In this context, [parallel.es](https://github.com/MichaReiser/parallel.es) migth be interesting.

**Comment by jiayihu** [comment]
@MichaReiser interesting library, thanks for suggesting! I'll have a look asap!

**Comment by MichaReiser** [comment]
@jiayihu If you know how you want to implement it from the point of your API we might work together to perform the integration.
